#!/bin/sh

while true;
do \
string="$(ps aux | grep "$(wmctrl -l -p | grep $(printf '%x' $(xdotool getwindowfocus)) | awk '{print $3}')" | head -n 1 | awk '{print $11}')" && \
string=( ${string[@]/\/*\//} ) && \
echo $string && \
sleep 1;
done
